### ISSUE TITLE
用你的 Demo 生成的 framework 没有文件

### ISSUE THREAD

**Issue by InsectQY** [maxfong/iOS-Library-Binary-Practice#1]

**Comment by maxfong** [comment]
下载master分支后直接pod update，然后打开iOSBinaryPractice.xcworkspace，里面的Framework没有文件？我刚测试了有的

**Comment by maxfong** [comment]
下载master分支后直接pod update，然后打开iOSBinaryPractice.xcworkspace，里面的Framework没有文件？我刚测试了有的 @InsectQY

**Comment by InsectQY** [comment]
![24ed192e-9c70-4603-b23f-9ade5cfd82f3](https://user-images.githubusercontent.com/22448409/47889133-5c92b280-de83-11e8-81f8-8659f783fecc.png)
![dbc20436-70f5-4ced-bcda-c23b7140ef4c](https://user-images.githubusercontent.com/22448409/47889137-5e5c7600-de83-11e8-9a47-3a1bacb4e1d5.png)
我 install 或者 update 完都没有，这个 Framework 是空的。

**Comment by maxfong** [comment]
@InsectQY 抱歉，Xcode9和Xcode10我测试了，CocoaPods 1.2.1和1.5.3也测试了，都OK，可以正常生成，你看一下这个目录内是否存在正常：/Users/用户/Library/Caches/CocoaPods/Pods/Release/iOSBinaryPractice/1.0.0-17d7a/Products/iOSBinaryPractice.framework

**Comment by maxfong** [comment]
@InsectQY 出现空文件应该是脚本编译失败了

**Comment by leibaozai** [comment]
我是直接执行的脚本，最后显示编译成功了，但是不存在文件。日志如下：

** BUILD SUCCEEDED ** [2.197 sec]

cp: build/Release-iphoneos/iOSBinaryPractice.framework/: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build/Release-iphoneos/iOSBinaryPractice.framework/iOSBinaryPractice (No such file or directory)

**Comment by maxfong** [comment]
@leibaozai 把`build_framework.sh`脚本内的 xcodebuild结尾的`clean build` 删掉后试试

**Comment by leibaozai** [comment]
@maxfong Xcode Version 11.6 (11E708)，pod --version 1.9.1 ,删除`clean build`也不行。`/Users/用户/Library/Caches/CocoaPods/Pods/Release/iOSBinaryPractice/1.0.0-17d7a/Products/iOSBinaryPractice.framework`这个目录下也是空的

**Comment by maxfong** [comment]
这个目录空的就是因为脚本没有成功，需要自己参考脚本写demo，肯定可以的

**Comment by leibaozai** [comment]
删除`clean build`，然后直接执行脚本`sh build_framework.sh`可以了。
